site_name: My Learning Journey
site_description: A collection of notes and resources on various topics.
site_author: rainuN
nav:
  - Home: index.md
  - About: about.md
  - Database:
      - Oracle: Database/questions.md
      - Snowflakes: Database/snowflakes.md
      - CockroachDB: Database/cockroachdb.md
      - PostgreSQL: Database/postgresql.md
  - Cloud:
      - GCP: Cloud/gcp.md
  - Container: 
      - Docker: Containerization/docker.md
      - Terraform: Containerization/terraform.md
  - Scripting:
      - UnixShell: Scripting/shellscripting.md
theme: readthedocs
plugins: 
  - search
  - open-in-new-tab