site_name: My Learning Journey
site_description: A collection of notes and resources on various topics.
site_author: rainuN
nav:
  - Home: index.md
  - About: about.md
  - Databases:
      - Installation & Setup:
          - PostgreSQL: Database/postgresql.md
          - CockroachDB: Database/cockroachdb.md
          - Oracle: Database/oracle.md
          - IBM DB2: Database/ibmdb2.md
      - Use Cases & Operations:
          - Google BigQuery: Database/gcbigquery.md
          - Data Lake: Database/datalake.md
  - Cloud:
      - Installation & Setup:
          - GCP Cloud SDK: Cloud/gcp.md
  - Containers & IAC:
      - Installation & Setup:
          - Docker: Containerization/docker.md
          - Terraform: Containerization/terraform.md
          - Kubernetes: Containerization/kubernetes.md
  - Scripting:
      - Use Cases & Commands:
          - Unix Shell: Scripting/shellscripting.md
  - Schedulers:
      - Installation & Setup:
          - Airflow: Scheduler/airflow.md
theme: readthedocs
plugins: 
  - search
  - open-in-new-tab